Cleaned up some of the mess Added test_for_file Fixed up and optimized test_for_dir Added test_perm Added setup_conf Updated comments Cleaned up if not installed do install.

diff --git a/docker-entrypoint b/docker-entrypoint
--- a/docker-entrypoint
+++ b/docker-entrypoint
@@ -9,28 +9,54 @@ function change_count() {
 	read LINECOUNT && echo "[Info] There were $LINECOUNT changes made."
 }
 
+function test_perm() {
+	## test octal permissions and assert them if they're wrong.
+	if [ ! $(stat -a $1) = $2 ]; then
+		echo "[Warn] $1 was not set to have the correct permissions $2"
+		echo "[RUN] chmod $2 $1"
+		chmod -v $2 $1
+	else
+		echo "[Info] $1 has the correct permissions"
+	fi
+	## Test group and user permissions and assert them if they're wrong.
+	if [ ! $($(stat -U $1):$(stat -G $1)) = $3 ]; then
+		echo "[Warn] $1 was not owned by the correct: user:group $3"
+		echo "[RUN] chown $1 $3"
+		chown -v $3 $1
+	else
+		echo "[Info] $1 is owned by the correct user:group: $3"
+	fi
+}
+
 ## If directory doesn't exist create it and set group perms.
+## Var $1 should be a directory.
+## Var $2 should be your octal permissions for said directory.
+## Var $3 should be your "user:group" names
 function test_for_dir() {
 	if [ ! -e '$1' ]; then
-			if [ "$(ls -A $1)" ]; then
-					echo "[warn] $1 is not Empty. It contains:" 1>&2
-					ls -A 1>&2
-					echo "[Info] Asserting permissions on $1 with test_for_dir function"
-					echo "[RUN] chmod -R 775 $1"
-					chmod -R 775 $1
-					echo "[RUN] chown -R $2 $1"
-					chown -R $2 $1
-			fi
-		else
-			echo "[Info] Directory $1 was missing, creating directory and setting permissions."
-			echo "[RUN] mkdir -pv $1"
-			mkdir -pv $1
-			echo "[Info] Setting permissions on newly created $1 with test_for_dir function"
-			echo "[RUN] chmod -R 775 $1"
-			chmod -R 775 $1
-			echo "[RUN] chown -R $2 $1"
-			chown -R $2 $1
-		fi
+		## Check if directory is empty
+		if [ "$(ls -A $1)" ]; then
+			echo "[warn] $1 is not Empty. It contains:" 1>&2
+			ls -A 1>&2
+			test_perm $1 $2 $3
+	fi
+	else
+		echo "[Info] Directory $1 was missing, creating directory and setting permissions."
+		echo "[RUN] mkdir -pv $1"
+		mkdir -pv $1
+		test_perm $1 $2 $3
+	fi
+}
+
+## This tests to see if a file exists and if it's permissions are correct or not.
+## Then it attempts to assert that files permissions.
+## Maybe add a test case to ensure that the file is critical or not.
+function test_for_file() {
+	if [ ! -f '$1' ]; then
+		echo [Info] File $1 not found.
+	else
+		test_perm $1 $2 $3
+	fi
 }
 
 function setup_conf() {
@@ -55,15 +81,17 @@ if [ ! "$(ls -A /etc/apache2)" ]; then
 		echo "[Info] copied apache2 configuration directory"
 fi
 
-# if Concrete5 is not yet installed, copy it into web root
+# if Concrete5 is not yet installed, copy it into web root.
+# This could be updated to be part of an upgrade mechanism.
 if [ ! -e '/var/www/html/config/concrete.php' ]; then
-		cd /var/www/html/
 		if [ "$(ls -A /var/www/html)" ]; then
 				echo "[warn] /var/www/html/ is not Empty. It contains:" 1>&2
 				ls -A 1>&2
 		fi
+
 		echo "[Info] Concrete5 Version: ${C5_VERSION}"
-		cp -r /usr/local/src/concrete5-${C5_VERSION}/* /var/www/html
+		chown -R root:www-data /usr/local/src/concrete5-${C5_VERSION}/
+		mv -r /usr/local/src/concrete5-${C5_VERSION}/* /var/www/html/
 
 		# change required permissions incl. for multi-lingual sites
 		test_for_dir /var/www/html/application/files/ "root:www-data"
@@ -76,15 +104,11 @@ if [ ! -e '/var/www/html/config/concrete.php' ]; then
 		echo "[Info] copied Concrete5 and set permissions"
 fi
 
-echo "Final perms check pre-launch"
-echo "[RUN] chown -R root:www-data /var/www/html"
 chown -R root:www-data /var/www/html
 echo "[RUN] chmod -R 775 /var/www/html/packages"
 chmod -R 775 /var/www/html/packages
 echo "[RUN] chmod -R 775 /var/www/html/application/config"
 chmod -R 775 /var/www/html/application/config
-
-
 
 # else default to run whatever the user wanted like "bash"
 exec "$@"
